Packages=rsync
Packages=fonts-noto-cjk
Packages=fonts-wqy-microhei
Packages=libasound2
Packages=libasound2-plugins
Packages=libdtkcore5
Packages=libdtkgui5
Packages=libdtkwidget5
Packages=libglu1-mesa
Packages=libgphoto2-6
Packages=libgphoto2-port12
Packages=libgssapi-krb5-2
Packages=libkrb5-3
Packages=libodbc1
Packages=libosmesa6
Packages=libsane1
Packages=libsdl2-2.0-0
Packages=libstdc++6
Packages=libx11-6
Packages=ocl-icd-libopencl1
Packages=p7zip-full
Packages=python3-dbus
Packages=apt
Packages=dpkg
Packages=ca-certificates
Packages=binutils
Packages=xz-utils
Packages=vim
Packages=libglib2.0-0
Packages=gsettings-desktop-schemas
Packages=x11-utils
Packages=procps
Packages=libc6
Packages=libdbus-1-3
Packages=libgcc-s1
Packages=libpulse0
Packages=libudev1
Packages=libwayland-client0
Packages=libxext6
Packages=libncurses6
Packages=deepin-elf-verify
Packages=libcap2-bin
Packages=libcups2
Packages=libnss-myhostname
Packages=libfontconfig1
Packages=libfreetype6
Packages=libgnutls30
Packages=libjpeg62-turbo
Packages=libxcomposite1
Packages=libxcursor1
Packages=libxfixes3
Packages=libxi6
Packages=libxinerama1
Packages=libxrandr2
Packages=libxrender1
Packages=libxxf86vm1
Packages=libgcc1
Packages=libgl1
Packages=libqt5core5a
Packages=libqt5gui5
Packages=libqt5widgets5
#Packages=libssl1.1
#Packages=libv4l-0  