Packages=rsync
Packages=fonts-noto-cjk
Packages=fonts-wqy-microhei
Packages=libasound2
Packages=libasound2-plugins
Packages=libdtkcore5
Packages=libdtkgui5
Packages=libdtkwidget5
Packages=libglu1-mesa
Packages=libgphoto2-6
Packages=libgphoto2-port12
Packages=libgssapi-krb5-2
Packages=libkrb5-3
Packages=libodbc1
Packages=libosmesa6
Packages=libsane1
Packages=libsdl2-2.0-0
#Packages=libssl1.1
Packages=libstdc++6
Packages=libx11-6
Packages=ocl-icd-libopencl1
Packages=p7zip-full
Packages=python3-dbus
